/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoalfa;


import java.applet.AudioClip;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;



/**
 *
 * @author ocana
 */
public class eje1VO extends javax.swing.JFrame {
    

    /**
     * Creates new form inicio
     */
   
    public eje1VO() {
        initComponents();
        jbtnalfa.setBackground(Color.BLUE);
        jbtnvocal.setBackground(Color.red);
        jbtnoraciones.setBackground(Color.green);
    }
    
    
    
    
    
    
    
    

    eje1VO(String name) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnalfa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtnvocal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jbtnoraciones = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jbtnoraciones1 = new javax.swing.JButton();
        jbtnoraciones2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 160));

        jbtnalfa.setBackground(new java.awt.Color(255, 255, 0));
        jbtnalfa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconovo/letter-e.png"))); // NOI18N
        jbtnalfa.setBorderPainted(false);
        jbtnalfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnalfaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnalfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 230, 280));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("el abecedario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, -1, -1));

        jbtnvocal.setBackground(new java.awt.Color(255, 255, 51));
        jbtnvocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconovo/letter-a (2).png"))); // NOI18N
        jbtnvocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnvocalActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnvocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 230, 280));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setText("Letra a");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        jbtnoraciones.setBackground(new java.awt.Color(255, 255, 0));
        jbtnoraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconovo/letter-o.png"))); // NOI18N
        jbtnoraciones.setBorderPainted(false);
        jbtnoraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnoracionesActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnoraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 170, 260, 280));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setText("oraciones");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, -1, -1));

        jbtnoraciones1.setBackground(new java.awt.Color(255, 255, 0));
        jbtnoraciones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconovo/letter-u.png"))); // NOI18N
        jbtnoraciones1.setBorderPainted(false);
        jbtnoraciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnoraciones1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnoraciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 250, 290));

        jbtnoraciones2.setBackground(new java.awt.Color(255, 255, 0));
        jbtnoraciones2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconovo/letter-i.png"))); // NOI18N
        jbtnoraciones2.setBorderPainted(false);
        jbtnoraciones2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnoraciones2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnoraciones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 170, 230, 270));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alfabetizacion (2).png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        jMenu1.setText("LAS VOCALES ");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("REGRESAR EL MENU DE SELECCION");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("REGRESA AL MENU DE SELCCION");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("HOME/INICIO");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/home.png"))); // NOI18N
        jMenuItem2.setText("REGRESAR AL INICO PRINCIPAL");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        inicio in = new inicio();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbtnvocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnvocalActionPerformed
        // TODO add your handling code here:
      
        ImageIcon icono = new ImageIcon("C:\\Users\\ocana\\OneDrive\\Documentos\\NetBeansProjects\\proyectoAlfa\\src\\iconovo\\vocala_1.jpeg");
        UIManager.put("OptionPane.background", Color.ORANGE);  // Fondo del panel
        UIManager.put("Panel.background", Color.blue);       // Fondo del cuadro de diálogo
        UIManager.put("OptionPane.messageForeground", Color.black); // Color del texto

        JOptionPane.showMessageDialog(null, "", "", JOptionPane.INFORMATION_MESSAGE,icono);
 
        
        
    }//GEN-LAST:event_jbtnvocalActionPerformed

    private void jbtnalfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnalfaActionPerformed
        // TODO add your handling code here:
        ImageIcon icono = new ImageIcon("C:\\Users\\ocana\\OneDrive\\Documentos\\NetBeansProjects\\proyectoAlfa\\src\\iconovo\\vocale.jpeg");
        UIManager.put("OptionPane.background", Color.ORANGE);  // Fondo del panel
        UIManager.put("Panel.background", Color.blue);       // Fondo del cuadro de diálogo
        UIManager.put("OptionPane.messageForeground", Color.black); // Color del texto

        JOptionPane.showMessageDialog(null, "", "", JOptionPane.INFORMATION_MESSAGE,icono);
 
    }//GEN-LAST:event_jbtnalfaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        menualfa mf = new menualfa();
        mf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jbtnoracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnoracionesActionPerformed
        // TODO add your handling code here:
            ImageIcon icono = new ImageIcon("C:\\Users\\ocana\\OneDrive\\Documentos\\NetBeansProjects\\proyectoAlfa\\src\\iconovo\\Vocalo.jpeg");
        UIManager.put("OptionPane.background", Color.ORANGE);  // Fondo del panel
        UIManager.put("Panel.background", Color.blue);       // Fondo del cuadro de diálogo
        UIManager.put("OptionPane.messageForeground", Color.black); // Color del texto

        JOptionPane.showMessageDialog(null, "", "", JOptionPane.INFORMATION_MESSAGE,icono);
   
    }//GEN-LAST:event_jbtnoracionesActionPerformed

    private void jbtnoraciones2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnoraciones2ActionPerformed
        // TODO add your handling code here:
             ImageIcon icono = new ImageIcon("C:\\Users\\ocana\\OneDrive\\Documentos\\NetBeansProjects\\proyectoAlfa\\src\\iconovo\\letrae.jpeg");
        UIManager.put("OptionPane.background", Color.ORANGE);  // Fondo del panel
        UIManager.put("Panel.background", Color.blue);       // Fondo del cuadro de diálogo
        UIManager.put("OptionPane.messageForeground", Color.black); // Color del texto

        JOptionPane.showMessageDialog(null, "", "", JOptionPane.INFORMATION_MESSAGE,icono);
    }//GEN-LAST:event_jbtnoraciones2ActionPerformed

    private void jbtnoraciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnoraciones1ActionPerformed
        // TODO add your handling code here:
        ImageIcon icono = new ImageIcon("C:\\Users\\ocana\\OneDrive\\Documentos\\NetBeansProjects\\proyectoAlfa\\src\\iconovo\\vocalu.jpeg");
        UIManager.put("OptionPane.background", Color.magenta);  // Fondo del panel
        UIManager.put("Panel.background", Color.blue);       // Fondo del cuadro de diálogo
        UIManager.put("OptionPane.messageForeground", Color.black); // Color del texto

        JOptionPane.showMessageDialog(null, "", "", JOptionPane.INFORMATION_MESSAGE,icono);

    }//GEN-LAST:event_jbtnoraciones1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eje1VO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eje1VO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eje1VO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eje1VO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eje1VO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton jbtnalfa;
    private javax.swing.JButton jbtnoraciones;
    private javax.swing.JButton jbtnoraciones1;
    private javax.swing.JButton jbtnoraciones2;
    private javax.swing.JButton jbtnvocal;
    // End of variables declaration//GEN-END:variables
}
