/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoalfa;

import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


/**
 *
 * @author ocana
 */
public class inicio extends javax.swing.JFrame {
    private String name;  

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        jMenu1.setFont(new Font("arial",Font.PLAIN,18));//cambiar color de letra en el jmenubar//
        jMenu1.setForeground(Color.red);    
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbnlogin = new javax.swing.JButton();
        jbtncontraseña = new javax.swing.JButton();
        jPascontraseña = new javax.swing.JPasswordField();
        jtxtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbnlogin.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jtbnlogin.setText("iniciar");
        jtbnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnloginActionPerformed(evt);
            }
        });
        getContentPane().add(jtbnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 730, 170, 70));

        jbtncontraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/hidden.png"))); // NOI18N
        jbtncontraseña.setBorderPainted(false);
        jbtncontraseña.setContentAreaFilled(false);
        jbtncontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncontraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtncontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(1680, 600, -1, -1));

        jPascontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPascontraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jPascontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 590, 360, 40));

        jtxtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnombreActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 480, 360, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo3.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INGRESA TU NOMNRE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 440, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INGRESA LA CONTRASEÑA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 550, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 150, 200, 210));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alfabetizacion.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        jMenu1.setText("INFORMACION");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("INFORMACION DE LA APP");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPascontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPascontraseñaActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jPascontraseñaActionPerformed

    private void jtxtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreActionPerformed

    private void jtbnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnloginActionPerformed
        // TODO add your handling code here:
        
     
    jtbnlogin.addActionListener(e -> {
    String name = jtxtnombre.getText(); // Obtiene el nombre
    String password = new String(jPascontraseña.getPassword()); // Obtiene la contraseña ingresada

    if (name.isEmpty()) { // Si el nombre está vacío
        JOptionPane.showMessageDialog(null, "Rellena el cuadro con tu nombre", "Error", JOptionPane.ERROR_MESSAGE);
    } else if (!password.equals("12345")) { // Si la contraseña no es "12345"
        JOptionPane.showMessageDialog(null, "Contraseña incorrecta", "Error", JOptionPane.ERROR_MESSAGE);  
    } else { // Si el nombre y la contraseña son correctos
         AudioClip Sound;
        Sound= java.applet.Applet.newAudioClip(getClass().getResource("/audio/busu.wav"));
        Sound.play();
              menualfa mn = new menualfa();
   mn.setVisible(true);
  mn.setNomnre(jtxtnombre.getText());
  this.setVisible(false);
       
   
}
});

   
  
        
    }//GEN-LAST:event_jtbnloginActionPerformed

    private void jbtncontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncontraseñaActionPerformed
        // TODO add your handling code here:
        
       ImageIcon eyeOpen = new ImageIcon("eye.png");
ImageIcon eyeClosed = new ImageIcon("hidden.png");
        jbtncontraseña.addActionListener(new ActionListener() {
    private boolean visible = false; // Estado inicial, contraseña oculta

    public void actionPerformed(ActionEvent e) {
        visible = !visible; // Alternar entre visible y oculto
        jPascontraseña.setEchoChar(visible ? (char) 0 : '•'); // Si visible, muestra la contraseña
        jbtncontraseña.setIcon(visible ? eyeOpen:eyeClosed ); // Cambia el icono del botón
}
});
    }//GEN-LAST:event_jbtncontraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPasswordField jPascontraseña;
    private javax.swing.JButton jbtncontraseña;
    private javax.swing.JButton jtbnlogin;
    private javax.swing.JTextField jtxtnombre;
    // End of variables declaration//GEN-END:variables
}
