/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoalfa;

import java.applet.AudioClip;

import java.awt.Color;





/**
 *
 * @author ocana
 */

public class menualfa extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    private String name;
    public menualfa() {
        initComponents();
        
        jbtnalfa.setBackground(Color.BLUE);
        jbtnvocal.setBackground(Color.red);
        jbtnoraciones.setBackground(Color.green);
    }
    public void setNomnre(String name){
        this.name = name;
        jLbNbienvida.setText("BIENVENIDO AL MENU ," +""+ name.toUpperCase());
    }
    
  

    menualfa(String name) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbNbienvida = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnalfa = new javax.swing.JButton();
        jbtnvocal = new javax.swing.JButton();
        jbtnoraciones = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbNbienvida.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLbNbienvida.setForeground(new java.awt.Color(255, 255, 255));
        jLbNbienvida.setText("BIenvenido usuario");
        getContentPane().add(jLbNbienvida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/userpe.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 80));

        jbtnalfa.setBackground(new java.awt.Color(255, 255, 0));
        jbtnalfa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btna.png"))); // NOI18N
        jbtnalfa.setBorderPainted(false);
        jbtnalfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnalfaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnalfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 490, 100));

        jbtnvocal.setBackground(new java.awt.Color(255, 255, 51));
        jbtnvocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btnv1.png"))); // NOI18N
        jbtnvocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnvocalActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnvocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 490, 100));

        jbtnoraciones.setBackground(new java.awt.Color(255, 255, 0));
        jbtnoraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btno.png"))); // NOI18N
        jbtnoraciones.setBorderPainted(false);
        jbtnoraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnoracionesActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnoraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 490, 100));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menal.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        jMenu2.setText("HOME/INICIO");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/home.png"))); // NOI18N
        jMenuItem2.setText("REGRESAR AL MENU PRINCIPAL");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        inicio in = new inicio();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbtnvocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnvocalActionPerformed
        // TODO add your handling code here:
     
        
         AudioClip Sound;
        Sound= java.applet.Applet.newAudioClip(getClass().getResource("/audio/buvo.wav"));
        Sound.play();
        vocales0 vo = new vocales0();
        vo.setVisible(true);
        this.setVisible(false);
         
         
    }//GEN-LAST:event_jbtnvocalActionPerformed

    private void jbtnalfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnalfaActionPerformed
        // TODO add your handling code here:}
      
       
     alfa0 af0= new alfa0();
     af0.setVisible(true);
     this.setVisible(false);
      AudioClip Sound;
       Sound= java.applet.Applet.newAudioClip(getClass().getResource("/audio/si.wav"));
        Sound.play();
      
      
       
        
        
        
        
    }//GEN-LAST:event_jbtnalfaActionPerformed

    private void jbtnoracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnoracionesActionPerformed
        // TODO add your handling code here:
       

  
        
    }//GEN-LAST:event_jbtnoracionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menualfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menualfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menualfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menualfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menualfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLbNbienvida;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton jbtnalfa;
    private javax.swing.JButton jbtnoraciones;
    private javax.swing.JButton jbtnvocal;
    // End of variables declaration//GEN-END:variables
}
