/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoalfa;


import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;



/**
 *
 * @author ocana
 */

public class vocales1 extends javax.swing.JFrame {
   private int puntos=0;
    private String icono;

    /**
     * Creates new form inicio
     */
   public vocales1(int puntos) {
    initComponents();
    this.puntos = puntos;
    etPuntos.setText("Puntos: " + puntos); // esta funciona y Muestra los puntos recibidos
}

   
    public vocales1() {
        initComponents();
    
    }
    
    
    
    
    
    
    
    

    vocales1(String name) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTXT1A = new javax.swing.JTextField();
        JTXTA2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        et1 = new javax.swing.JLabel();
        et2 = new javax.swing.JLabel();
        etPuntos = new javax.swing.JLabel();
        etEstrellas = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EJERCICIO PONIENDO LA VOCAL A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, -1, -1));

        JTXT1A.setFont(new java.awt.Font("Tahoma", 1, 61)); // NOI18N
        JTXT1A.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTXT1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTXT1AActionPerformed(evt);
            }
        });
        getContentPane().add(JTXT1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 150, 130));

        JTXTA2.setFont(new java.awt.Font("Tahoma", 1, 61)); // NOI18N
        JTXTA2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(JTXTA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 570, 140, 130));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CHECAR RESPUESTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 790, 210, 70));
        getContentPane().add(et1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 130, 60));
        getContentPane().add(et2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 480, 120, 80));

        etPuntos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etPuntos.setForeground(new java.awt.Color(255, 255, 255));
        etPuntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etPuntos.setText("Puntos: 0");
        getContentPane().add(etPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 40, 440, 60));

        etEstrellas.setText("jLabel2");
        getContentPane().add(etEstrellas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 300, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vo1.png"))); // NOI18N
        fondo.setText("dsgg");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1920, 1120));

        jMenu1.setText("LAS VOCALES ");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("REGRESAR EL MENU DE SELECCION");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("REGRESA AL MENU DE SELCCION");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("HOME/INICIO");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/home.png"))); // NOI18N
        jMenuItem2.setText("REGRESAR AL INICO PRINCIPAL");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        inicio in = new inicio();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        menualfa mf = new menualfa();
        mf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void JTXT1AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTXT1AActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_JTXT1AActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String te1 = JTXT1A.getText();
        String te2 = JTXTA2.getText();
         boolean correcto1 = false;
    boolean correcto2 = false;
    

        StringBuilder errorCampos = new StringBuilder();
        
        if (te1.equalsIgnoreCase("a")) {
    et1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check/check-mark.png")));
    correcto1=true;
} else {
    et1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check/mala.png")));
    errorCampos.append("Caja1, ");
}

if (te2.equalsIgnoreCase("a")) {
    et2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check/check-mark.png")));
    correcto2=true;
} else {
    et2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check/mala.png")));
    errorCampos.append("Caja2, ");
}
      

  // Ahora verificamos si los dos están correctos
    if (correcto1 && correcto2) {
        puntos++; // suma 1 punto
        JOptionPane.showMessageDialog(this, "¡Correcto! Puntos: " + puntos);
        etPuntos.setText("Puntos: " + puntos); // ACTUALIZA la etiqueta de puntos
      
   
        
        // Aquí cambias al siguiente frame
        vocales2 siguienteFrame = new vocales2(puntos); // supongamos que tu siguiente frame se llama vocales2
        siguienteFrame.setVisible(true);
        this.setVisible(false);
    } else {
        JOptionPane.showMessageDialog(this, "Algunas respuestas están incorrectas. Inténtalo de nuevo.");

}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vocales1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vocales1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vocales1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vocales1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vocales1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTXT1A;
    private javax.swing.JTextField JTXTA2;
    private javax.swing.JLabel et1;
    private javax.swing.JLabel et2;
    private javax.swing.JLabel etEstrellas;
    private javax.swing.JLabel etPuntos;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
